### ISSUE TITLE
crouton-new vs fork

### ISSUE THREAD

**Issue by wickwire** [jakeloggins/crouton-new#5]
Hi,

Why the need for a **crouton-new** project, as opposed to forking the original project by **edfungus**? Wouldn't it be easier to incorporate the scheduler feature in your fork, later submitting (or not) your updates via pull request, to the main project?

Your added work is valuable in my opinion, but in terms of project organization it would probably make more sense to add to the existing main project, rather than start a new one, for each new feature that each user thinks of.

Please consider forks and pull requests on your future community development, it makes your work more visible and better contributes to the overall project growth.

In any case, thank you for your effort!

**Comment by jakeloggins** [comment]
I was just about to reply to you in the other thread. The short answer is that at first I wasn't sure what I was doing. You're right, I should have forked it instead.

However, as I kept going it became clear that I intend for this project to require a raspberry pi or equivalent system to host a local MQTT server, with helper scripts (such as the scheduler) listening in and reacting as needed. This opens up new possibilities that can't be done on a front-end only system. The docs of the original project make clear that it's a front-end only intended to feed into a future cloud MQTT option. I felt it was going in a different enough direction to remain separate and it had been a month since I posted my original issue.

The scheduler uses a backend helper script that only loosely interfaces with the crouton dashboard. Everything runs through MQTT, so that in the future you can set schedules with slack, text message, email, or other inputs.

Make sense?

**Comment by wickwire** [comment]
Yes, I see where you're heading with it - and with that in mind, my suggestion would be to have your scheduler solution in a modular fashion as well, while perhaps including some predefined hooks for Crouton or even any other front-end solution to your personal liking, so that users could still resort to it, have it up and running as a whole for scheduling, but not be limited to any one front-end in particular. And in the end, get to name it for the awesome project you'll have it be!

That said, I guess it could be more complex to develop this way and again, as with any community development out there, everyone else is already lucky enough to have something while expecting nothing, so thank you for your efforts and hard work on this and please view these comments as just suggestions, nothing more...!

Regardless, do consider publishing any non-scheduler enhancements/specific fixes to the original crouton project, as it would be most appreciated I'm sure! :)

**Comment by jakeloggins** [comment]
I was thinking about separating everything out into projects like this:
- backend helpers. I'm developing more now, but they would work as you mentioned.
- MQTT path standard. I made significant changes to the path structure from the original project too.
- front-end with included interfaces for the helpers

But it hasn't been a pressing issue because you are probably the only person who has noticed this repo. :)

**Comment by jakeloggins** [comment]
Hey, are you on gitter? I mentioned you. Swing by and let's chat.
